### PR TITLE
Flask

### PR DESCRIPTION
**Pull request by lawrenceChege**
check on changes made and leave a comment

### CODE REVIEW

**Comment by indungu** [comment]
For starters, that is a long commit message you have over there, [here's](https://chris.beams.io/posts/git-commit/) an article to help you with that.

**Comment by indungu** [comment]
From the look of it you also seem to be tracking your `virtual environment` which should not be the case.
To fix this just create a `.gitignore` on the root of your repository's directory tree then add `venv/` to the file and save. You should also add `.idea/` to your `.gitignore` to stop tracking of your code editor workspace setup files as well.

**Comment by kevinsamoei** [comment]
Add a `.gitignore` file to avoid  the unnecessary files and folders for example `.idea/` and virtual environment. Also, ignore `.xml` files that come with using an IDE like vscode or pycharm

**Comment by kevinsamoei** [comment]
Your file changes are too much. I think it is due to this extra folders like the `.idea/` and `.xml` files

**Comment by lawrenceChege** [comment]
thanks guys let me work on that

**Pull request merged**
